# Generated by Django 6.0.3 on 2026-04-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='article',
            field=models.IntegerField(null=True),
        ),
    ]
